name: auto_animated
description: Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
version: 2.2.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/auto_animated

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
